'use client';

import { motion, useScroll, useTransform } from 'framer-motion';
import { ArrowRight, Zap, Activity, Users, Star, CheckCircle2, MapPin, Instagram, Facebook } from 'lucide-react';
import CustomCursor from './components/CustomCursor';
import Image from 'next/image';

export default function Page() {
    const { scrollYProgress } = useScroll();
    const y = useTransform(scrollYProgress, [0, 1], ['0%', '50%']);

    return (
        <main className="min-h-screen bg-[#050505] overflow-x-hidden text-white cursor-none">
            <CustomCursor />

            {/* === NAVBAR === */}
            <nav className="fixed top-0 left-0 right-0 z-50 flex justify-between items-center px-6 py-4 md:px-12 backdrop-blur-sm border-b border-white/5 bg-black/50">
                <div className="relative w-32 h-10">
                    {/* Logo Real del Cliente */}
                    <Image
                        src="/prospectos/360sports/logo.png"
                        alt="360 Sports Logo"
                        fill
                        className="object-contain filter brightness-0 invert"
                    />
                </div>
                <div className="hidden md:flex gap-8 text-[10px] font-bold tracking-widest uppercase text-zinc-400">
                    <a href="#" className="hover:text-[#ccff00] transition-colors">Programas</a>
                    <a href="#" className="hover:text-[#ccff00] transition-colors">Sedes</a>
                    <a href="#" className="hover:text-[#ccff00] transition-colors">Team</a>
                </div>
                <button className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest bg-white text-black px-4 py-2 hover:bg-[#ccff00] transition-colors">
                    Free Pass <ArrowRight className="w-3 h-3" />
                </button>
            </nav>

            {/* === HERO SECTION (NEON SWEAT STYLE) === */}
            <section className="relative h-screen flex items-center justify-center overflow-hidden">
                {/* Parallax Background generated by AI */}
                <motion.div style={{ y }} className="absolute inset-0 z-0">
                    <div className="absolute inset-0 bg-black/40 z-10" />
                    <Image
                        src="/prospectos/360sports/hero_bg.png"
                        alt="360 Gym Atmosphere"
                        fill
                        className="object-cover"
                        priority
                    />
                </motion.div>

                {/* Noise Overlay */}
                <div className="absolute inset-0 bg-transparent opacity-10 pointer-events-none z-10" style={{ backgroundImage: 'url("data:image/svg+xml,%3Csvg viewBox=%220 0 200 200%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cfilter id=%22noiseFilter%22%3E%3CfeTurbulence type=%22fractalNoise%22 baseFrequency=%220.65%22 numOctaves=%223%22 stitchTiles=%22stitch%22/%3E%3C/filter%3E%3Crect width=%22100%25%22 height=%22100%25%22 filter=%22url(%23noiseFilter)%22 opacity=%221%22/%3E%3C/svg%3E")' }}></div>

                <div className="relative z-20 px-6 max-w-7xl mx-auto w-full mt-20">
                    <div className="inline-flex items-center gap-3 border border-[#ccff00]/30 bg-black/30 backdrop-blur-md px-3 py-1 rounded-full mb-6">
                        <span className="w-1.5 h-1.5 rounded-full bg-[#ccff00] animate-pulse"></span>
                        <span className="text-[#ccff00] font-mono text-[10px] tracking-widest uppercase">The Revolution of Fitness</span>
                    </div>

                    <h1 className="text-6xl md:text-9xl font-black uppercase tracking-tighter leading-[0.85] mb-6">
                        Train Like<br />
                        <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#ccff00] to-white/60">A Machine</span>
                    </h1>

                    <div className="flex flex-col md:flex-row items-end justify-between gap-12 border-l-2 border-[#ccff00] pl-6 md:pl-8 ml-2">
                        <p className="text-zinc-300 max-w-md text-base md:text-lg font-light leading-relaxed">
                            Olvídate del gimnasio tradicional. Fusionamos <strong className="text-white">Kinesiología Deportiva</strong>, <strong className="text-white">Entrenamiento Funcional</strong> y <strong className="text-white">Alto Rendimiento</strong> en un solo ecosistema.
                        </p>

                        <div className="flex gap-4">
                            <button className="px-8 py-4 bg-[#ccff00] text-black font-black uppercase tracking-wider text-xs hover:bg-white transition-colors">
                                Start Now
                            </button>
                            <button className="px-8 py-4 border border-white text-white font-black uppercase tracking-wider text-xs hover:bg-white hover:text-black transition-colors">
                                View Programs
                            </button>
                        </div>
                    </div>
                </div>
            </section>

            {/* === METRICS / PROOF === */}
            <section className="bg-[#ccff00] py-12 relative overflow-hidden">
                <div className="max-w-7xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-8">
                    <div className="text-black">
                        <h3 className="text-4xl font-black tracking-tighter">04</h3>
                        <p className="text-xs font-bold uppercase tracking-widest mt-1 opacity-60">Sedes Activas</p>
                    </div>
                    <div className="text-black">
                        <h3 className="text-4xl font-black tracking-tighter">+850</h3>
                        <p className="text-xs font-bold uppercase tracking-widest mt-1 opacity-60">Atletas</p>
                    </div>
                    <div className="text-black">
                        <h3 className="text-4xl font-black tracking-tighter">100%</h3>
                        <p className="text-xs font-bold uppercase tracking-widest mt-1 opacity-60">Kinesiología</p>
                    </div>
                    <div className="text-black flex items-center justify-end">
                        <img src="/prospectos/360sports/logo.png" className="h-8 brightness-0 opacity-20" alt="logo watermark" />
                    </div>
                </div>
            </section>

            {/* === METHODOLOGY (Real Data) === */}
            <section className="py-32 px-6 bg-zinc-950 relative">
                <div className="max-w-7xl mx-auto">
                    <div className="flex items-end justify-between mb-20 border-b border-white/10 pb-8">
                        <h2 className="text-5xl md:text-7xl font-black uppercase tracking-tighter">
                            The <span className="text-stroke-white text-transparent">Method</span>
                        </h2>
                        <p className="text-right text-zinc-500 text-xs font-mono max-w-xs hidden md:block">
                            SYSTEM_V.2.0 // <br />OPTIMIZED FOR HUMAN PERFORMANCE
                        </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                        {/* Card 1 */}
                        <div className="group relative bg-zinc-900 border border-white/5 hover:border-[#ccff00]/50 transition-colors p-8 min-h-[400px] flex flex-col justify-between">
                            <div>
                                <div className="bg-zinc-800 w-12 h-12 flex items-center justify-center rounded-sm mb-6 text-[#ccff00]">
                                    <Activity />
                                </div>
                                <h3 className="text-2xl font-black uppercase italic mb-4">Functional<br />Circuit</h3>
                                <p className="text-zinc-400 text-sm leading-relaxed">
                                    Entremiento de variabilidad constante. Fuerza, resistencia y potencia en circuitos de 60 minutos diseñados para quemar y construir.
                                </p>
                            </div>
                            <div className="w-full h-[1px] bg-zinc-800 mt-8 group-hover:bg-[#ccff00] transition-colors" />
                        </div>

                        {/* Card 2 */}
                        <div className="group relative bg-zinc-900 border border-white/5 hover:border-[#ccff00]/50 transition-colors p-8 min-h-[400px] flex flex-col justify-between mt-0 md:-mt-12 bg-gradient-to-b from-zinc-800/50 to-zinc-900">
                            <div>
                                <div className="bg-[#ccff00] w-12 h-12 flex items-center justify-center rounded-sm mb-6 text-black">
                                    <Users />
                                </div>
                                <h3 className="text-2xl font-black uppercase italic mb-4 text-[#ccff00]">Kinesiología<br />Deportiva</h3>
                                <p className="text-zinc-300 text-sm leading-relaxed">
                                    No solo entrenas, te recuperas. Nuestro equipo de kinesiólogos monitorea tu biomecánica para prevenir lesiones y mejorar tu rendimiento real.
                                </p>
                            </div>
                            <div className="w-full h-[1px] bg-zinc-800 mt-8 group-hover:bg-[#ccff00] transition-colors" />
                        </div>

                        {/* Card 3 */}
                        <div className="group relative bg-zinc-900 border border-white/5 hover:border-[#ccff00]/50 transition-colors p-8 min-h-[400px] flex flex-col justify-between">
                            <div>
                                <div className="bg-zinc-800 w-12 h-12 flex items-center justify-center rounded-sm mb-6 text-[#ccff00]">
                                    <Zap />
                                </div>
                                <h3 className="text-2xl font-black uppercase italic mb-4">Functional<br />Strong</h3>
                                <p className="text-zinc-400 text-sm leading-relaxed">
                                    Levantamiento olímpico y fuerza bruta. Diseñado para quienes buscan romper sus propias marcas y construir un físico atlético y funcional.
                                </p>
                            </div>
                            <div className="w-full h-[1px] bg-zinc-800 mt-8 group-hover:bg-[#ccff00] transition-colors" />
                        </div>
                    </div>
                </div>
            </section>

            {/* === IMAGE GRID / VIBE === */}
            <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 h-[60vh]">
                <div className="relative group overflow-hidden">
                    <Image src="https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=2070&auto=format&fit=crop" alt="Gym" fill className="object-cover transition-transform duration-700 group-hover:scale-110 grayscale group-hover:grayscale-0" />
                    <div className="absolute inset-0 bg-black/20 group-hover:bg-transparent transition-colors" />
                </div>
                <div className="relative group overflow-hidden lg:col-span-2">
                    <Image src="https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?q=80&w=2069&auto=format&fit=crop" alt="Weights" fill className="object-cover transition-transform duration-700 group-hover:scale-110 grayscale group-hover:grayscale-0" />
                    <div className="absolute inset-x-0 bottom-0 p-8 bg-gradient-to-t from-black/80 to-transparent">
                        <h4 className="text-3xl font-black uppercase italic">Hardcore Environment</h4>
                    </div>
                </div>
                <div className="relative group overflow-hidden">
                    <Image src="https://images.unsplash.com/photo-1549476464-37392f717541?q=80&w=1974&auto=format&fit=crop" alt="Ropes" fill className="object-cover transition-transform duration-700 group-hover:scale-110 grayscale group-hover:grayscale-0" />
                </div>
            </section>


            {/* === MEMBERSHIP PLANS === */}
            <section className="py-32 px-6 max-w-7xl mx-auto">
                <div className="text-center mb-20">
                    <h2 className="text-4xl md:text-6xl font-black uppercase tracking-tighter mb-4">Choose Your <span className="text-[#ccff00]">Weapon</span></h2>
                    <p className="text-zinc-400 max-w-2xl mx-auto">Planes flexibles adaptados a tu nivel de compromiso. Sin letras chicas.</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-center">
                    {/* Plan 1 */}
                    <div className="bg-zinc-900/50 border border-white/5 p-8 rounded-lg hover:bg-zinc-900 transition-colors">
                        <h3 className="text-xl font-bold uppercase tracking-widest text-zinc-400 mb-2">Basic</h3>
                        <div className="text-3xl font-black mb-6">Functional</div>
                        <ul className="space-y-4 mb-8 text-sm text-zinc-300">
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Acceso a clases Functional</li>
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Uso Open Gym (Horario Valle)</li>
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Camarines y Duchas</li>
                        </ul>
                        <button className="w-full py-4 border border-zinc-700 text-white font-bold uppercase tracking-widest text-xs hover:border-white transition-colors">Select Plan</button>
                    </div>

                    {/* Plan 2 (Featured) */}
                    <div className="bg-black border border-[#ccff00] p-10 rounded-lg transform md:-translate-y-4 shadow-[0_0_50px_-10px_rgba(204,255,0,0.3)] relative">
                        <div className="absolute top-0 right-0 bg-[#ccff00] text-black text-[10px] font-black uppercase px-3 py-1 tracking-widest">Most Popular</div>
                        <h3 className="text-xl font-bold uppercase tracking-widest text-[#ccff00] mb-2">Pro</h3>
                        <div className="text-4xl font-black mb-6">Plan Exclusivo</div>
                        <ul className="space-y-4 mb-8 text-sm text-white">
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> <strong>Acceso Ilimitado</strong> a todo</li>
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Evaluación Kinesiológica Mensual</li>
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Nutrición Personalizada</li>
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Free Pass para un amigo x mes</li>
                        </ul>
                        <button className="w-full py-4 bg-[#ccff00] text-black font-black uppercase tracking-widest text-xs hover:bg-white transition-colors">Start Free Trial</button>
                    </div>

                    {/* Plan 3 */}
                    <div className="bg-zinc-900/50 border border-white/5 p-8 rounded-lg hover:bg-zinc-900 transition-colors">
                        <h3 className="text-xl font-bold uppercase tracking-widest text-zinc-400 mb-2">Elite</h3>
                        <div className="text-3xl font-black mb-6">Alto Rendimiento</div>
                        <ul className="space-y-4 mb-8 text-sm text-zinc-300">
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Planificación Competitiva</li>
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Kine Rehab Ilimitado</li>
                            <li className="flex gap-3"><CheckCircle2 className="w-4 h-4 text-[#ccff00]" /> Coach 1-on-1 Asignado</li>
                        </ul>
                        <button className="w-full py-4 border border-zinc-700 text-white font-bold uppercase tracking-widest text-xs hover:border-white transition-colors">Contact Us</button>
                    </div>
                </div>
            </section>

            {/* === LOCATIONS / CTA === */}
            <section className="bg-white text-black py-24 px-6 relative overflow-hidden">
                <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-12 relative z-10">
                    <div>
                        <h2 className="text-5xl md:text-8xl font-black uppercase tracking-tighter leading-none mb-6">
                            Find Your<br />Ground
                        </h2>
                        <div className="flex gap-8 text-sm font-bold uppercase tracking-tight">
                            <div className="flex items-center gap-2"><MapPin className="w-4 h-4" /> Las Condes</div>
                            <div className="flex items-center gap-2"><MapPin className="w-4 h-4" /> Vitacura</div>
                            <div className="flex items-center gap-2"><MapPin className="w-4 h-4" /> Chicureo</div>
                        </div>
                    </div>
                    <div>
                        <div className="bg-black text-white p-8 md:p-12 max-w-md skew-x-[-5deg]">
                            <h3 className="text-2xl font-black uppercase italic text-[#ccff00] mb-4 skew-x-[5deg]">First Class is Free</h3>
                            <p className="text-zinc-400 mb-8 skew-x-[5deg]">Ven a probar la experiencia 360 Sports sin compromiso. Siente la diferencia de entrenar con profesionales.</p>
                            <button className="w-full py-4 bg-[#ccff00] text-black font-black uppercase tracking-widest text-xs hover:bg-white hover:text-black transition-colors skew-x-[5deg]">
                                Book Session Now
                            </button>
                        </div>
                    </div>
                </div>
                {/* Background Pattern */}
                <div className="absolute top-0 right-0 w-1/2 h-full bg-[url('/prospectos/360sports/hero_bg.png')] bg-cover opacity-10 grayscale mix-blend-multiply"></div>
            </section>

            {/* === FOOTER === */}
            <footer className="bg-zinc-950 text-white py-16 px-6 border-t border-white/10">
                <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-8">
                    <div className="relative w-24 h-8 grayscale opacity-50">
                        <Image src="/prospectos/360sports/logo.png" alt="Logo" fill className="object-contain" />
                    </div>
                    <div className="flex gap-6">
                        <a href="#" className="p-2 border border-white/20 rounded-full hover:bg-[#ccff00] hover:text-black hover:border-[#ccff00] transition-all"><Instagram className="w-4 h-4" /></a>
                        <a href="#" className="p-2 border border-white/20 rounded-full hover:bg-[#ccff00] hover:text-black hover:border-[#ccff00] transition-all"><Facebook className="w-4 h-4" /></a>
                    </div>
                    <p className="text-[10px] uppercase tracking-widest text-zinc-600">
                        360 Sports © 2026. Made by HojaCero.
                    </p>
                </div>
            </footer>
        </main>
    );
}
